/**
 * Generates lesson content and merges into lessons.json
 * Run: node scripts/generate-lessons.js
 */
const fs = require('fs');
const path = require('path');

const OUT = path.join(__dirname, '../src/data/lessons.json');
const CURRICULUM_31_60 = require('./curriculum-31-60');
const CURRICULUM_61_100 = require('./curriculum-61-100');

const CURRICULUM = [
  { day: 4, title: 'Asking for Directions', theme: 'travel', sentence: 'Excuse me, can you tell me how to get to the railway station?', hindi: 'माफ़ कीजिए, क्या आप बता सकते हैं रेलवे स्टेशन कैसे जाएँ?', pattern: 'Excuse me, can you tell me how to get to [place]?', words: [['Excuse','A polite word before asking','माफ़ कीजिए','eks-KYOOS'],['Direction','The way to go','दिशा','di-REK-shun'],['Station','A place where trains stop','स्टेशन','STAY-shun'],['Turn','To change direction','मुड़ना','TERN'],['Left','Opposite of right','बाएँ','LEFT']], conv: ['Excuse me, where is the railway station?','Go straight and turn left.','Thank you! How far is it?'], wotd: ['Journey','A trip from one place to another','यात्रा','Life is a beautiful journey.'] },
  { day: 5, title: 'At the Doctor', theme: 'health', sentence: 'I have a headache and fever since yesterday.', hindi: 'मुझे कल से सिरदर्द और बुखार है।', pattern: 'I have a [problem] since [time].', words: [['Doctor','A person who treats sick people','डॉक्टर','DOK-ter'],['Headache','Pain in the head','सिरदर्द','HED-ayk'],['Fever','High body temperature','बुखार','FEE-ver'],['Medicine','Something that makes you feel better','दवाई','MED-i-sin'],['Rest','To relax and sleep','आराम','REST']], conv: ['What is the problem?','I have a headache and fever.','Take this medicine and rest.'], wotd: ['Healthy','In good health','स्वस्थ','Eat vegetables to stay healthy.'] },
  { day: 6, title: 'Making Phone Calls', theme: 'communication', sentence: 'Hello, may I speak to Mr. Sharma, please?', hindi: 'नमस्ते, क्या मैं शर्मा जी से बात कर सकता हूँ?', pattern: 'Hello, may I speak to [name], please?', words: [['Call','To phone someone','फ़ोन करना','KAWL'],['Speak','To talk','बोलना','SPEEK'],['Message','Written or spoken information','संदेश','MES-ij'],['Number','Phone digits','नंबर','NUM-ber'],['Hold','Wait on the phone','रुकना','HOHLD']], conv: ['Hello, Sharma residence.','May I speak to Mr. Sharma?','Please hold. I will call him.'], wotd: ['Connect','To join or reach someone','जुड़ना','I will connect you now.'] },
  { day: 7, title: 'At the Bank', theme: 'money', sentence: 'I would like to open a savings account, please.', hindi: 'मैं बचत खाता खोलना चाहता हूँ।', pattern: 'I would like to open a [type] account, please.', words: [['Bank','A place to keep money safely','बैंक','BANK'],['Account','Your money record at a bank','खाता','a-KAWNT'],['Deposit','To put money in the bank','जमा करना','di-POZ-it'],['Withdraw','To take money out','निकालना','with-DRAW'],['Balance','Money left in your account','बैलेंस','BAL-ans']], conv: ['How can I help you?','I want to open a savings account.','Please fill this form.'], wotd: ['Savings','Money kept for future use','बचत','Start your savings today.'] },
  { day: 8, title: 'Talking About Family', theme: 'family', sentence: 'I have two brothers and one sister.', hindi: 'मेरे दो भाई और एक बहन है।', pattern: 'I have [number] [family member] and [number] [family member].', words: [['Family','Parents, siblings, relatives','परिवार','FAM-i-lee'],['Brother','A male sibling','भाई','BRUTH-er'],['Sister','A female sibling','बहन','SIS-ter'],['Parents','Mother and father','माता-पिता','PAIR-ents'],['Married','Having a husband or wife','विवाहित','MAR-eed']], conv: ['Tell me about your family.','I have two brothers and one sister.','That is a lovely family!'], wotd: ['Together','With each other','साथ में','We eat dinner together.'] },
  { day: 9, title: 'Weather Talk', theme: 'daily', sentence: 'It is very hot today. I think it will rain.', hindi: 'आज बहुत गर्मी है। मुझे लगता है बारिश होगी।', pattern: 'It is very [weather] today. I think it will [weather].', words: [['Hot','High temperature','गर्म','HOT'],['Cold','Low temperature','ठंडा','KOHLD'],['Rain','Water falling from sky','बारिश','RAYN'],['Sunny','Bright with sun','धूप','SUN-ee'],['Cloudy','Sky full of clouds','बादल','KLOW-dee']], conv: ['Nice weather today!','Yes, but it looks like rain.','Take an umbrella!'], wotd: ['Forecast','Weather prediction','पूर्वानुमान','Check the weather forecast.'] },
  { day: 10, title: 'At School', theme: 'education', sentence: 'My favourite subject is English and I love reading.', hindi: 'मेरा पसंदीदा विषय अंग्रेज़ी है और मुझे पढ़ना पसंद है।', pattern: 'My favourite subject is [subject] and I love [activity].', words: [['Subject','A topic you study','विषय','SUB-jekt'],['Teacher','A person who teaches','शिक्षक','TEE-cher'],['Homework','Work to do at home','गृहकार्य','HOHM-wurk'],['Exam','A test of knowledge','परीक्षा','ig-ZAM'],['Class','A group of students learning','कक्षा','KLAS']], conv: ['What is your favourite subject?','I like English the most.','That is wonderful! Keep practicing.'], wotd: ['Knowledge','What you learn and know','ज्ञान','Knowledge is power.'] },
  { day: 11, title: 'Shopping for Clothes', theme: 'shopping', sentence: 'Do you have this shirt in a medium size?', hindi: 'क्या यह शर्ट मीडियम साइज़ में है?', pattern: 'Do you have this [item] in a [size] size?', words: [['Shirt','Clothing for upper body','शर्ट','SHURT'],['Size','Small, medium, or large','साइज़','SIZ'],['Try','To test if something fits','पहनकर देखना','TRY'],['Fit','To be the right size','फ़िट होना','FIT'],['Colour','Red, blue, green, etc.','रंग','KUL-er']], conv: ['Can I help you?','Do you have this in medium?','Yes! Would you like to try it on?'], wotd: ['Fashion','Style of clothing','फ़ैशन','Fashion changes every season.'] },
  { day: 12, title: 'Using Public Transport', theme: 'travel', sentence: 'Which bus goes to the city centre?', hindi: 'कौन सी बस सिटी सेंटर जाती है?', pattern: 'Which [vehicle] goes to [place]?', words: [['Bus','A large public vehicle','बस','BUS'],['Ticket','Paper that lets you travel','टिकट','TIK-et'],['Stop','Where the bus halts','बस स्टॉप','STOP'],['Fare','Price of travel','किराया','FAIR'],['Platform','Where you wait for a train','प्लेटफ़ॉर्म','PLAT-form']], conv: ['Where do you want to go?','Which bus goes to city centre?','Take bus number 42.'], wotd: ['Commute','Daily travel to work','आवागमन','My commute takes one hour.'] },
  { day: 13, title: 'At the Office', theme: 'job', sentence: 'I have a meeting at ten o clock this morning.', hindi: 'आज सुबह दस बजे मेरी मीटिंग है।', pattern: 'I have a meeting at [time] this [morning/afternoon].', words: [['Meeting','A work discussion','मीटिंग','MEE-ting'],['Colleague','A person you work with','सहकर्मी','KOL-eeg'],['Deadline','Last date to finish work','समय सीमा','DED-line'],['Report','A written work summary','रिपोर्ट','ri-PORT'],['Boss','The person in charge','बॉस','BOS']], conv: ['Good morning! Ready for the meeting?','Yes, I prepared the report.','Great work!'], wotd: ['Professional','Related to work','पेशेवर','Dress professionally for interviews.'] },
  { day: 14, title: 'Cooking at Home', theme: 'daily', sentence: 'I am cooking rice and dal for dinner tonight.', hindi: 'मैं आज रात के खाने के लिए चावल और दाल बना रहा हूँ।', pattern: 'I am cooking [food] for dinner tonight.', words: [['Cook','To prepare food','पकाना','KOOK'],['Kitchen','Room where you cook','रसोई','KICH-en'],['Recipe','Instructions to make food','रेसिपी','RES-i-pee'],['Taste','Flavor of food','स्वाद','TAYST'],['Ingredients','Things used to cook','सामग्री','in-GREE-dee-ents']], conv: ['What are you cooking?','Rice and dal for dinner.','That sounds delicious!'], wotd: ['Delight','Great pleasure','आनंद','Cooking is my delight.'] },
  { day: 15, title: 'Weekend Plans', theme: 'social', sentence: 'What are you doing this weekend?', hindi: 'इस वीकेंड तुम क्या कर रहे हो?', pattern: 'What are you doing this [weekend/evening]?', words: [['Weekend','Saturday and Sunday','वीकेंड',' WEEK-end'],['Plan','What you intend to do','योजना','PLAN'],['Movie','A film you watch','फ़िल्म','MOO-vee'],['Park','A green public place','पार्क','PARK'],['Friend','A person you like','दोस्त','FREND']], conv: ['Any plans for the weekend?','I am going to watch a movie.','Sounds fun! Enjoy!'], wotd: ['Relax','To rest and unwind','आराम करना','Relax on the weekend.'] },
  { day: 16, title: 'At the Pharmacy', theme: 'health', sentence: 'I need medicine for cough and cold.', hindi: 'मुझे खाँसी और जुकाम की दवाई चाहिए।', pattern: 'I need medicine for [problem] and [problem].', words: [['Pharmacy','Shop that sells medicine','दवाखाना','FAR-ma-see'],['Cough','Air pushed from throat','खाँसी','KOF'],['Cold','Illness with runny nose','जुकाम','KOHLD'],['Tablet','Solid medicine to swallow','गोली','TAB-let'],['Prescription','Doctor written medicine list','नुस्खा','pri-SKRIP-shun']], conv: ['How can I help?','I need cough and cold medicine.','Do you have a prescription?'], wotd: ['Recover','To get healthy again','ठीक होना','Rest well to recover fast.'] },
  { day: 17, title: 'Writing an Email', theme: 'job', sentence: 'I am writing to apply for the job position.', hindi: 'मैं नौकरी के पद के लिए आवेदन करने लिख रहा हूँ।', pattern: 'I am writing to apply for the [position].', words: [['Email','Electronic message','ईमेल','EE-mayl'],['Apply','To request a job','आवेदन करना','a-PLY'],['Attach','To add a file','संलग्न करना','a-TACH'],['Subject','Email title line','विषय','SUB-jekt'],['Reply','To answer a message','जवाब देना','ri-PLY']], conv: ['Did you send the application email?','Yes, I attached my resume.','Good! Wait for their reply.'], wotd: ['Formal','Official and polite style','औपचारिक','Use formal language in emails.'] },
  { day: 18, title: 'Sports and Hobbies', theme: 'leisure', sentence: 'I play cricket every Sunday with my friends.', hindi: 'मैं हर रविवार दोस्तों के साथ क्रिकेट खेलता हूँ।', pattern: 'I play [sport] every [day] with my friends.', words: [['Cricket','A popular Indian sport','क्रिकेट','KRIK-et'],['Hobby','Activity you enjoy','शौक','HOB-ee'],['Play','To do a sport or game','खेलना','PLAY'],['Team','Group playing together','टीम','TEEM'],['Win','To succeed in a game','जीतना','WIN']], conv: ['What is your hobby?','I play cricket on Sundays.','Cricket is great! Who is your favourite player?'], wotd: ['Passion','Strong love for something','जुनून','Follow your passion.'] },
  { day: 19, title: 'Renting a House', theme: 'daily', sentence: 'I am looking for a two bedroom flat near the metro.', hindi: 'मुझे मेट्रो के पास दो कमरे का फ़्लैट चाहिए।', pattern: 'I am looking for a [type] near [place].', words: [['Rent','Monthly payment for a home','किराया','RENT'],['Flat','An apartment','फ़्लैट','FLAT'],['Landlord','Owner of the house','मकान मालिक','LAND-lord'],['Deposit','Advance payment for rent','जमा राशि','di-POZ-it'],['Metro','Underground train system','मेट्रो','MET-roh']], conv: ['Are you looking for a flat?','Yes, near the metro station.','I know a good place. Let me show you.'], wotd: ['Neighbourhood','Area where you live','मोहल्ला','Choose a safe neighbourhood.'] },
  { day: 20, title: 'Job Interview Basics', theme: 'job', sentence: 'I have three years of experience in sales.', hindi: 'मुझे बिक्री में तीन साल का अनुभव है।', pattern: 'I have [number] years of experience in [field].', words: [['Experience','Knowledge from past work','अनुभव','ik-SPEER-ee-ens'],['Skill','Ability you are good at','कौशल','SKIL'],['Resume','Document about your work history','बायोडाटा','REZ-u-may'],['Salary','Money you earn from work','वेतन','SAL-a-ree'],['Qualification','Your education and degrees','योग्यता','kwol-i-fi-KAY-shun']], conv: ['Tell me about your experience.','I have three years in sales.','Impressive! Why do you want this job?'], wotd: ['Achieve','To successfully complete a goal','हासिल करना','You can achieve your dreams.'] },
  { day: 21, title: 'At the Gym', theme: 'health', sentence: 'I come to the gym three times a week.', hindi: 'मैं सप्ताह में तीन बार जिम आता हूँ।', pattern: 'I come to the gym [number] times a week.', words: [['Gym','Place to exercise','जिम','JIM'],['Exercise','Physical activity for health','व्यायाम','EK-ser-syz'],['Strong','Having power and health','मज़बूत','STRONG'],['Weight','Heavy objects for training','वज़न','WAYT'],['Trainer','Person who guides exercise','ट्रेनर','TRAY-ner']], conv: ['First time at the gym?','Yes. I want to get stronger.','Welcome! I will show you around.'], wotd: ['Fitness','Being physically healthy','फ़िटनेस','Fitness needs consistency.'] },
  { day: 22, title: 'Online Shopping', theme: 'shopping', sentence: 'I ordered a phone online and it will arrive tomorrow.', hindi: 'मैंने ऑनलाइन फ़ोन ऑर्डर किया, कल आएगा।', pattern: 'I ordered a [item] online and it will arrive [when].', words: [['Order','To buy something online','ऑर्डर','OR-der'],['Delivery','Bringing goods to your home','डिलीवरी','di-LIV-a-ree'],['Track','To follow your package status','ट्रैक करना','TRAK'],['Return','To send back a product','वापस करना','ri-TURN'],['Discount','Reduced price','छूट','DIS-kownt']], conv: ['Did your order arrive?','Not yet. It comes tomorrow.','You can track it on the app.'], wotd: ['Convenient','Easy and helpful','सुविधाजनक','Online shopping is convenient.'] },
  { day: 23, title: 'Festivals and Culture', theme: 'social', sentence: 'We celebrate Diwali with lights and sweets.', hindi: 'हम दीवाली रोशनी और मिठाई से मनाते हैं।', pattern: 'We celebrate [festival] with [tradition] and [tradition].', words: [['Festival','A special celebration day','त्योहार','FES-ti-val'],['Celebrate','To enjoy a special day','मनाना','SEL-a-brayt'],['Tradition','Custom passed through generations','परंपरा','tra-DISH-un'],['Sweets','Candy and desserts','मिठाई','SWEETS'],['Guest','A person you invite home','मेहमान','GEST']], conv: ['How do you celebrate Diwali?','We light lamps and share sweets.','That sounds beautiful!'], wotd: ['Heritage','Cultural traditions of a community','विरासत','Proud of our heritage.'] },
  { day: 24, title: 'Complaining Politely', theme: 'daily', sentence: 'Sorry, but the food is cold. Could you heat it, please?', hindi: 'माफ़ कीजिए, खाना ठंडा है। गर्म कर देंगे?', pattern: 'Sorry, but [problem]. Could you [solution], please?', words: [['Sorry','Polite word when complaining','माफ़ कीजिए','SOR-ee'],['Problem','Something wrong','समस्या','PROB-lum'],['Replace','To give a new one instead','बदलना','ri-PLAYS'],['Refund','Money returned','रिफ़ंड','REE-fund'],['Polite','Kind and respectful','विनम्र','po-LYT']], conv: ['Is everything okay?','The soup is cold. Could you heat it?','Of course! I am very sorry.'], wotd: ['Satisfaction','Feeling happy with service','संतुष्टि','Customer satisfaction matters.'] },
  { day: 25, title: 'Technology Basics', theme: 'daily', sentence: 'Can you help me connect to the WiFi?', hindi: 'क्या आप वाई-फ़ाई से जोड़ने में मदद करेंगे?', pattern: 'Can you help me [action] the [technology]?', words: [['WiFi','Wireless internet','वाई-फ़ाई','WAI-fai'],['Password','Secret code for access','पासवर्ड','PAS-wurd'],['App','Application on phone','ऐप','AP'],['Download','To get from internet','डाउनलोड','DOWN-lohd'],['Update','New version of software','अपडेट','UP-dayt']], conv: ['I cannot connect to WiFi.','What is the password?','It is on the router. Let me show you.'], wotd: ['Digital','Related to computers and internet','डिजिटल','We live in a digital world.'] },
  { day: 26, title: 'At the Airport', theme: 'travel', sentence: 'My flight to Delhi is at six in the evening.', hindi: 'दिल्ली की मेरी उड़ान शाम छह बजे है।', pattern: 'My flight to [city] is at [time].', words: [['Flight','A trip by aeroplane','उड़ान','FLYT'],['Passport','Travel identity document','पासपोर्ट','PAS-port'],['Luggage','Bags you travel with','सामान','LUG-ij'],['Boarding','Getting on the plane','बोर्डिंग','BOR-ding'],['Gate','Airport exit to the plane','गेट','GAYT']], conv: ['May I see your boarding pass?','Here it is. Gate number twelve.','Thank you. Have a safe flight!'], wotd: ['Destination','Place you are going to','मंज़िल','Delhi is my destination.'] },
  { day: 27, title: 'Feelings and Emotions', theme: 'social', sentence: 'I feel nervous before an interview.', hindi: 'इंटरव्यू से पहले मैं घबराता हूँ।', pattern: 'I feel [emotion] before [event].', words: [['Happy','Feeling joy','खुश','HAP-ee'],['Nervous','Worried and tense','घबराया','NUR-vus'],['Excited','Very happy and eager','उत्साहित','ik-SY-ted'],['Worried','Anxious about something','चिंतित','WUR-eed'],['Confident','Sure of yourself','आत्मविश्वासी','KON-fi-dent']], conv: ['How do you feel about the interview?','I am a little nervous.','That is normal. You will do great!'], wotd: ['Emotion','A strong feeling','भावना','Control your emotions.'] },
  { day: 28, title: 'Giving Opinions', theme: 'social', sentence: 'In my opinion, English practice is very important.', hindi: 'मेरे विचार में, अंग्रेज़ी अभ्यास बहुत ज़रूरी है।', pattern: 'In my opinion, [topic] is very important.', words: [['Opinion','What you think about something','राय','o-PIN-yun'],['Think','To use your mind','सोचना','THINK'],['Agree','To have the same view','सहमत','a-GREE'],['Disagree','To have a different view','असहमत','dis-a-GREE'],['Believe','To feel something is true','विश्वास','bi-LEEV']], conv: ['What do you think about daily practice?','I think it is very important.','I completely agree with you!'], wotd: ['Perspective','Your point of view','दृष्टिकोण','Everyone has a different perspective.'] },
  { day: 29, title: 'Making Appointments', theme: 'daily', sentence: 'Can I book an appointment for Friday at three PM?', hindi: 'क्या मैं शुक्रवार तीन बजे अपॉइंटमेंट ले सकता हूँ?', pattern: 'Can I book an appointment for [day] at [time]?', words: [['Appointment','A fixed meeting time','अपॉइंटमेंट','a-POINT-ment'],['Book','To reserve a time slot','बुक करना','BOOK'],['Available','Free and open','उपलब्ध','a-VAY-la-bl'],['Cancel','To stop a planned meeting','रद्द करना','KAN-sel'],['Confirm','To say yes it is fixed','पुष्टि करना','kon-FIRM']], conv: ['I need a dentist appointment.','Friday at three is available.','Perfect! Please confirm it.'], wotd: ['Schedule','Plan of times and dates','कार्यक्रम','Check your schedule daily.'] },
  { day: 30, title: 'Month One Review', theme: 'review', sentence: 'I have learned many new words and I can speak better now.', hindi: 'मैंने कई नए शब्द सीखे और अब बेहतर बोल सकता हूँ।', pattern: 'I have learned [what] and I can [ability] now.', words: [['Learn','To gain knowledge','सीखना','LERN'],['Improve','To get better','सुधार','im-PROOV'],['Practice','To do repeatedly','अभ्यास','PRAK-tis'],['Progress','Moving forward','प्रगति','PROG-res'],['Proud','Happy about achievement','गर्व','PROWD']], conv: ['You finished 30 days! How do you feel?','I am proud. My English is improving!','Amazing! Keep going to Day 100!'], wotd: ['Milestone','An important achievement point','मील का पत्थर','Day 30 is a big milestone!'] },
];

function buildLesson(c) {
  const [w1,w2,w3,w4,w5] = c.words;
  const mkWord = ([word, meaning, meaningHindi, phonetic]) => ({
    word, meaning, meaningHindi, phonetic,
    example: `I use the word ${word.toLowerCase()} every day.`
  });
  return {
    day: c.day,
    title: c.title,
    theme: c.theme,
    level: c.day <= 30 ? 'beginner' : c.day <= 60 ? 'intermediate' : 'advanced',
    words: c.words.map(mkWord),
    sentence: { english: c.sentence, hindi: c.hindi, pattern: c.pattern },
    conversation: {
      title: c.title,
      lines: [
        { speaker: 'other', text: c.conv[0] },
        { speaker: 'user', text: c.conv[1], hint: 'Try saying this.' },
        { speaker: 'other', text: c.conv[2] },
      ]
    },
    quiz: [
      { id: `d${c.day}q1`, question: `What is the main topic of Day ${c.day}?`, options: [c.title, 'Cooking only', 'Sports only', 'Nothing'], correctIndex: 0, explanation: `Today we learned about ${c.title}.` },
      { id: `d${c.day}q2`, question: `Complete: ${c.pattern.split('[')[0].trim()}...`, options: [c.words[0][0], 'Random', 'Nothing', 'Maybe'], correctIndex: 0, explanation: `Key word: ${c.words[0][0]}.` },
      { id: `d${c.day}q3`, question: `Which word means "${c.words[1][1]}"?`, options: [c.words[0][0], c.words[1][0], c.words[2][0], c.words[3][0]], correctIndex: 1, explanation: `${c.words[1][0]} means ${c.words[1][1].toLowerCase()}.` },
    ],
    wordOfTheDay: { word: c.wotd[0], meaning: c.wotd[1], meaningHindi: c.wotd[2], example: c.wotd[3] }
  };
}

const existing = JSON.parse(fs.readFileSync(OUT, 'utf8'));
const ALL_CURRICULUM = [...CURRICULUM, ...CURRICULUM_31_60, ...CURRICULUM_61_100];
ALL_CURRICULUM.forEach(c => { existing[String(c.day)] = buildLesson(c); });
fs.writeFileSync(OUT, JSON.stringify(existing, null, 2));
console.log(`✅ Lessons updated: ${Object.keys(existing).length} days total`);

// Copy to mvp folder for deployment
const mvpOut = path.join(__dirname, '../mvp/lessons.json');
fs.copyFileSync(OUT, mvpOut);
console.log(`✅ Copied to mvp/lessons.json`);
